travel_app/urls.py
from django.urls import path
from travel_app import views
#TEMPLATE URLS
app_name = 'travel_app'
urlpatterns=[
    path(r'^signup/',views.signup,name='signup'),
    path(r'^user_login/',views.user_login,name='user_login'),
    path(r'^index/',views.index,name='index'),
    path(r'^newq/', views.newq, name='newq'),
    path(r'^destination/',views.destination,name='destination'),
#r'^users/(?P<user_id>\d+)/$'
]

traverCity/urls.py
from django.contrib import admin
from django.urls import include, path
from travel_app import views

urlpatterns = [
    path(r'',views.index,name='index'),
    # url(r'^$',views.newq,name='newq'),
    path(r'admin/', admin.site.urls),
    path(r'^travel_app/',include('travel_app.urls',namespace="travel_app")),
    path(r'^user_logout/',views.user_logout,name='user_logout'),

]

travel_app/models.py
from django.db import models
from django.contrib.auth.models import User
# from phonenumber_field import formfields
# from phonenumber_field.phonenumber import PhoneNumber, to_python, validate_region
# from phonenumber_field.validators import validate_international_phonenumber

class Usersignup(models.Model):

    user = models.OneToOneField(User,default=None,on_delete=models.PROTECT)

    #additional
    name = models.CharField(null=False, blank = False, max_length=264)

    #email = models.EmailField(null=False, blank=False, default='null')

    #username = models.CharField(null=False, blank=False, default='uname',max_length=10)

    #password = models.CharField(null=False, blank=False, max_length=50, default='null')

    contact_no = models.IntegerField(null=False, blank=False)

    dob = models.DateField(null=False, blank=False)

    gender = models.CharField(max_length=8)

    marital_status = models.CharField(max_length=8)

    #dom = models.DateField(null=False, blank=False)

    def __str__(self):
         return self.user.username


class Questionnaire(models.Model):

    username = models.ForeignKey(Usersignup, default=None, on_delete=models.CASCADE)
    adventure = models.IntegerField(null=False, default=0)
    heritage = models.IntegerField(null=False, default=0)
    wildlife = models.IntegerField(null=False, default=0)
    nature = models.IntegerField(null=False, default=0)
    pilgrimage = models.IntegerField(null=False, default=0)
    couple = models.IntegerField(null=False, default=0)
    friends = models.IntegerField(null=False, default=0)
    family = models.IntegerField(null=False, default=0)
    winter = models.IntegerField(null=False, default=0)
    spring = models.IntegerField(null=False, default=0)
    summer = models.IntegerField(null=False, default=0)
    monsoon = models.IntegerField(null=False, default=0)
    autumn = models.IntegerField(null=False, default=0)
    young = models.IntegerField(null=False, default=0)
    mid_age = models.IntegerField(null=False, default=0)
    old = models.IntegerField(null=False, default=0)
    visited_state = models.CharField(null=False, default='null',max_length=20)
    visited_city = models.CharField(null=False, default='null',max_length=20)
    rate_place = models.IntegerField(null=False, default=0)
    budget = models.IntegerField(null=False, default=0)

    def __str__(self):
        if self.username==None:
            return "ERROR-CUSTOMER USERNAME IS NULL"
        return self.username

# class Citydatabase(models.Model):
#
#     placeid = models.IntegerField(null=False, default='null')
#     city = models.CharField(null=False, default='null', max_length=20)
#     state = models.CharField(null=False, default='null', max_length=20)
#     type = models.CharField(null=False, default='null',max_length=20)
#
#     def __str__(self):
#         return self.placeid
#
# class Ratingdatabase(models.Model):
#
#     userid = models.IntegerField(null=False, default='null')
#     placeid = models.IntegerField(null=False, default='null')
#     rating = models.IntegerField(null=False, default=0)
#     timestamp = models.DateField(null=False, default='null')
#
#     def __str__(self):
#         return self.userid

travel_app/forms.py
from django import forms
from django.contrib.auth.models import User
from travel_app.models import Usersignup  , Questionnaire

GENDER_CHOICES = [
   ('Male', 'Male'),
   ('Female', 'Female')
]

MARITAL_CHOICES = [
    ('Single', 'Single'),
    ('Married', 'Married')
]

INTEGER_CHOICES= [tuple([x,x]) for x in range(1,6)]

class UserForm(forms.ModelForm):
    username = forms.CharField(label='Username') #, widget=forms.TextInput(attrs={'class' : 'special'}))
    email = forms.EmailField(label='Email', widget=forms.TextInput(attrs={'class' : 'myemailclass'}))
    password = forms.CharField(label='Password',widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UsersignupForm(forms.ModelForm):

    gender= forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect())
    marital_status= forms.ChoiceField(choices=MARITAL_CHOICES, widget=forms.RadioSelect())
    #DOM=forms.DateField(input_formats=['%d/%m/%y'])

    class Meta():
        model = Usersignup
        fields = ('name','contact_no','dob','gender','marital_status')
        # widgets = {'gender': forms.RadioSelect(choices=[('M', 'Male'),('F', 'Female')]),'marital_status':forms.RadioSelect(choices=[('S', 'Single'),('M', 'Married')]), 'password': forms.PasswordInput()}
        # preferred_drink = forms.ChoiceField(choices=PREFERRED_DRINK_CHOICES,
        #                                 widget=forms.RadioSelect())

class QuestionnaireForm(forms.ModelForm):

    adventure = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    heritage = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    wildlife = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    nature = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    pilgrimage = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    couple = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    friends = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    family = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    winter = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    spring = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    summer = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    monsoon = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    autumn = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    young = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    mid_age = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    old = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    #visited_state = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    #visited_city = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    rate_place = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))
    #budget = forms.IntegerField(widget=forms.Select(choices=INTEGER_CHOICES))

    class Meta():
        model = Questionnaire
        fields = ('username','adventure','heritage','wildlife','nature','pilgrimage','couple','friends','family','winter','spring','summer','monsoon','autumn','young','mid_age','old','visited_state','visited_city','rate_place','budget')

travel_app/views.py
from django.shortcuts import render
from travel_app.forms import UserForm,UsersignupForm, QuestionnaireForm
from travel_app.models import Usersignup  ,Questionnaire
from travel_app.GettingStarted import Get

#from datarel import datarel

###
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required  #****
from django.contrib.auth.backends import ModelBackend, UserModel

# Create your views here.
def index(request):
    return render(request, 'travel_app/index.html')

def newq(request):
    return render(request, 'travel_app/newq.html')

def destination(request):
    Getting_Started = Get()
    # console.log(Getting_Started.recommendations)
    print("sfsdf")
    print(Getting_Started[0])
    gs0 = Getting_Started[1]
    gs1 = Getting_Started[2]
    gs2 = Getting_Started[3]
    gs3 = Getting_Started[4]
    gs4 = Getting_Started[5]
    gs5 = Getting_Started[6]
    gs6 = Getting_Started[7]
    return render(request, 'travel_app/destination.html',{'gs0':gs0,'gs1':gs1,'gs2':gs2,'gs3':gs3,'gs4':gs4,'gs5':gs5,'gs6':gs6})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def signup(request):

    registered = False
    #username = None
    if request.method == 'POST':

        # userregister=Userregistration()
        # userregister.name = request.POST.get('name')
        # userregister.email = request.POST.get('email')
        # userregister.username = request.POST.get('username')
        # userregister.password = request.POST.get('password')
        # userregister.contact_no = request.POST.get('phone')
        # userregister.dob = request.POST.get('birthday')
        # userregister.gender = request.POST.get('gender')
        # userregister.marital_status = request.POST.get('status')
        #userregister.dom = request.POST.get('anniversary')
        #print(userregister.Gender)

        user_form = UserForm(data=request.POST)
        usersignup_form = UsersignupForm(data=request.POST)

        if user_form.is_valid() and usersignup_form.is_valid():
            # username = request.POST.get('username')
            # print(username)
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            usersignup = usersignup_form.save(commit=False)
            usersignup.user = user
            usersignup.save()
        # userregister.set_password(user.set_password)
        # userregister.save()

            registered = True

        else:
            print(user_form.errors, usersignup_form.errors)


    else:
        user_form = UserForm()
        usersignup_form = UsersignupForm()
        # userregister = UserregistrationForm()
    return render(request,'travel_app/signup.html',
                            {'user_form':user_form,
                             'usersignup_form':usersignup_form,
                             #'username': username,
                              'registered':registered})


def user_login(request):

      if request.method == 'POST':
          username = request.POST.get('username')
          password = request.POST.get('password')

          user = authenticate(username=username, password=password)
          print(user)
          if user is not None:
              print("Hey")
              if user.is_active:
                  print("Hello")
                  login(request,user)
                  return HttpResponseRedirect(reverse('user_home'))
              else:
                  print("else first")
                  return HttpResponse("ACCOUNT NOT ACTIVE")

          else:
              print("Someone tried to login and failed!")
              print("username: {} and password: {} ".format(username,password))
              return HttpResponse("invalid login details supplied")
      else:
          return render(request,'travel_app/user_login.html',{})

def newq(request):

    filled = False

    # username = request.get('username')
    #print(username)
    if request.method == 'POST':

        ques = QuestionnaireForm(request.POST)
        #username = post.objects.get(username=username)
        #print(username)
        if ques.is_valid():

            instance = ques.save(commit=False)
            instance.username = request.user
            instance.save
            ques.adventure = request.POST.get('adventure')
            ques.heritage = request.POST.get('heritage')
            ques.wildlife = request.POST.get('wildlife')
            ques.nature = request.POST.get('nature')
            ques.pilgrimage = request.POST.get('pilgrimage')
            ques.couple = request.POST.get('couple')
            ques.friends = request.POST.get('friends')
            ques.family = request.POST.get('family')
            ques.winter = request.POST.get('winter')
            ques.spring = request.POST.get('spring')
            ques.summer = request.POST.get('summer')
            ques.monsoon = request.POST.get('monsoon')
            ques.autumn = request.POST.get('autumn')
            ques.young = request.POST.get('young')
            ques.mid_age = request.POST.get('midage')
            ques.old = request.POST.get('old')
            ques.visited_state = request.POST.get('stt')
            ques.visited_city = request.POST.get('city')
            ques.rate_place = request.POST.get('place')
            ques.budget = request.POST.get('budget')

        else:
            print(ques.errors)

        filled = True

    else:
        ques = QuestionnaireForm()

    return render(request,'travel_app/newq.html',
                    {'filled':filled})


# class EmailBackend(ModelBackend):  # pylint: disable=too-few-public-methods
#     '''
#     Authentication backend class which authenticates the user against his
#     e-mail address instead of his username.
#     '''
#
#     def authenticate(self, username=None, password=None, **kwargs):  # pylint: disable=unused-argument
#         '''
#         Authenticate the user via his e-mail address.
#
#         :param str username: The username used to authenticate
#         :param str password: The password used to authenticate
#         :return: When successful, the User model is returned
#         :rtype: User model or None
#         '''
#         try:
#             user = UserModel.objects.get(email=username)
#         except UserModel.DoesNotExist:
#             return None
#         else:
#             if user.check_password(password) and self.user_can_authenticate(user):
#                 return user
#
#         return None

templates/travel_app/signup.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
	<title>traverCity- a Travel Recommendation Website</title>
	<meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href={% static "vendor/mdi-font/css/material-design-iconic-font.min.css" %} rel="stylesheet" media="all">
    <link href={% static "vendor/font-awesome-4.7/css/font-awesome.min.css" %} rel="stylesheet" media="all">
	<link rel="stylesheet" type="text/css" href={% static "vendor/select2/select2.min.css" %}/>
	<link rel="stylesheet" type="text/css" href={% static "vendor/daterangepicker/daterangepicker.css" %}/>
  <link href={% static "css/signupmain.css" %} rel="stylesheet" media="all"/>
</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
    <!--<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.html">traverCity</a>
	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav nav ml-auto">
	          <li class="nav-item"><a href="index.html" class="nav-link"><span>Home</span></a></li>
	          <li class="nav-item"><a href="index.html#services-section" class="nav-link"><span>Services</span></a></li>
	          <li class="nav-item"><a href="index.html#about-section" class="nav-link"><span>About</span></a></li>
	          <li class="nav-item"><a href="index.html#destination-section" class="nav-link"><span>Destination</span></a></li>
	          <li class="nav-item"><a href="index.html#blog-section" class="nav-link"><span>Blog</span></a></li>
			  <li class="nav-item"><a href="index.html#contact-section" class="nav-link"><span>Contact</span></a></li>
			  <li class="nav-item"><a href="login.html" class="nav-link"><span>Login</span></a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>
    -->

	<div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
									 {% if registered %}
									 	<h1><center>Thanks for registering!</center></h1>
										<!-- <h1>{{ username }}</h1> -->
									 	<!-- <script type="text/javascript"> -->
									 	<button class="btn btn--radius-2 btn--green" onclick="send()">Move to Questionnaire...CLick Here</button>
									 	<!-- </script> -->
									 {% else %}
                    <h2 class="title"><center><b>REGISTRATION FORM</b>	</center></h2>
                    <form method="POST">
										{% csrf_token %}
										<table border = '1' width = 100%>

										{{ user_form.as_table }}
										{{ usersignup_form.as_table }}
									</table>
                        <!-- <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Name</label>
                                    <input class="input--style-4" type="text" name="name">
                                </div>
                            </div>

                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">E-mail</label>
                                    <input class="input--style-4" type="email" name="email">
                                </div>
                            </div>
														<div class="col-2">
                                <div class="input-group">
                                    <label class="label">Username</label>
                                    <input class="input--style-4" type="text" name="username">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Password</label>
                                    <input class="input--style-4" type="password" name="password">
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Contact Number</label>
                                    <input class="input--style-4" type="text" name="phone">
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-1">
                                <div class="input-group">
                                    <label class="label">Date of Birth</label>
                                    <div class="input-group-icon">
                                        <input class="input--style-4 js-datepicker1"  type="text" name="birthday">
                                        <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar1"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="col-1">
                                <div class="input-group">
                                    <label class="label">Gender</label>
                                    <div class="p-t-10">
                                        <label class="radio-container m-r-45">Male
                                            <input type="radio" checked="checked" name="gender">
                                            <span class="checkmark"></span>
                                        </label>
                                        <label class="radio-container">Female
                                            <input type="radio" name="gender">
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-1">
                                <div class="input-group">
                                    <div class="input-group">
                                        <label class="label">Marital Status</label>
                                        <div class="p-t-10">
                                            <label class="radio-container m-r-45">Single
                                                <input type="radio" checked="checked" name="status" id = "single">
                                                <span class="checkmark"></span>
                                            </label>
                                            <label class="radio-container">Married
                                                <input type="radio" name="status" id="married">
                                                <span class="checkmark"></span>
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="input-group" id="dom" style="display: none">
                                    <label class="label">Date of Marriage</label>
                                    <div class="input-group-icon">
                                        <input class="input--style-4 js-datepicker2" type="text" name="anniversary">
                                        <i class="zmdi zmdi-calendar-note input-icon js-btn-calendar2"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="p-t-15">
                            <input class="btn btn--radius-2 btn--green" type="submit" value="Sign Up" onclick="send()">
                        </div> -->
												<input class="btn btn--radius-2 btn--green" type="submit" value="Sign Up">
												 <!-- onclick="send()"> -->
                    </form>
									 {% endif %}
                </div>
            </div>
        </div>
    </div>

	<!--<div id="dropDownSelect1"></div>-->

	<script src={% static "vendor/jquery/jquery-3.2.1.min.js" %}></script>
	<script src={% static "vendor/animsition/js/animsition.min.js" %}></script>
	<script src={% static "vendor/bootstrap/js/popper.js" %}></script>
	<script src={% static "vendor/bootstrap/js/bootstrap.min.js" %}></script>
	<script src={% static "vendor/select2/select2.min.js" %}></script>
	<script src={% static "vendor/daterangepicker/moment.min.js" %}></script>
	<script src={% static "vendor/daterangepicker/daterangepicker.js" %}></script>
	<script src={% static "vendor/countdowntime/countdowntime.js" %}></script>
  <script src={% static "js/global.js" %}></script>
  <script src={% static "js/loginmain.js" %}></script>
  <script>
  $('#married').change(function()
  {
      $('#dom').toggle();
  });
	function send()
	{
			//console.log("Username:" , username)
			window.location.href="{% url 'travel_app:newq' %}" }
  </script>

</body>
</html>

templates/travel_app/user_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>traverCity- a Travel Recommendation Website</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href={% static "images/icons/favicon.ico" %}/>
	<link rel="stylesheet" type="text/css" href={% static "vendor/bootstrap/css/bootstrap.min.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "fonts/font-awesome-4.7.0/css/font-awesome.min.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "fonts/Linearicons-Free-v1.0.0/icon-font.min.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "vendor/animate/animate.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "vendor/css-hamburgers/hamburgers.min.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "vendor/animsition/css/animsition.min.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "vendor/select2/select2.min.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "vendor/daterangepicker/daterangepicker.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "css/util.css" %}>
	<link rel="stylesheet" type="text/css" href={% static "css/main.css" %}>
</head>
<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light site-navbar-target" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="index.html">traverCity</a>
	      <button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav nav ml-auto">
	          <li class="nav-item"><a href="index.html" class="nav-link"><span>Home</span></a></li>
	          <li class="nav-item"><a href="index.html#services-section" class="nav-link"><span>Services</span></a></li>
	          <li class="nav-item"><a href="index.html#about-section" class="nav-link"><span>About</span></a></li>
	          <!-- <li class="nav-item"><a href="index.html#destination-section" class="nav-link"><span>Destination</span></a></li> -->
	          <!--<li class="nav-item"><a href="#hotel-section" class="nav-link"><span>Hotel</span></a></li>
	          <li class="nav-item"><a href="#restaurant-section" class="nav-link"><span>Restaurant</span></a></li>-->
	          <li class="nav-item"><a href="index.html#blog-section" class="nav-link"><span>Blog</span></a></li>
			  <li class="nav-item"><a href="index.html#contact-section" class="nav-link"><span>Contact</span></a></li>
			  <li class="nav-item"><a href="login.html" class="nav-link"><span>Login</span></a></li>
	        </ul>
	      </div>
	    </div>
	  </nav>


	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form" action="{% url 'travel_app:destination' %}" method='POST'>
					{% csrf_token %}
					<span class="login100-form-title p-b-34">
						Account Login
					</span>

					<div class="wrap-input100 rs1-wrap-input100 validate-input m-b-20" data-validate="Type user name">
						<input class="input100" type="text" name="username" placeholder="Username">
						<span class="focus-input100"></span>
					</div>
					<div class="wrap-input100 rs2-wrap-input100 validate-input m-b-20" data-validate="Type password">
						<input class="input100" type="password" name="password" placeholder="Password">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn" type="submit" name="" value="Login">
							Sign In
						</button>
					</div>

					<div class="w-full text-center p-t-27 p-b-239">
						<span class="txt1">
							Forgot
						</span>

						<a href="#" class="txt2">
							User name / password?
						</a>
					</div>

					<div class="w-full text-center">
						<a href="{% url 'travel_app:signup' %}" class="txt3">
							Sign Up
						</a>
					</div>
				</form>

				<div class="login100-more" style="background-image: url({% static 'images/bg-01.jpg' %});"></div>
			</div>
		</div>
	</div>



	<div id="dropDownSelect1"></div>

	<script src={% static "vendor/jquery/jquery-3.2.1.min.js" %}></script>
	<script src={% static "vendor/animsition/js/animsition.min.js" %}></script>
	<script src={% static "vendor/bootstrap/js/popper.js" %}></script>
	<script src={% static "vendor/bootstrap/js/bootstrap.min.js" %}></script>
	<script src={% static "vendor/select2/select2.min.js" %}></script>
	<script>
		$(".selection-2").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});
	</script>
	<script src={% static "vendor/daterangepicker/moment.min.js" %}></script>
	<script src={% static "vendor/daterangepicker/daterangepicker.js" %}></script>
	<script src={% static "vendor/countdowntime/countdowntime.js" %}></script>
	<script src={% static "js/loginmain.js" %}></script>

</body>
</html>